### ISSUE TITLE
Add example with %CD%

### ISSUE THREAD

**Issue by axelboc** [remcoros/vscode-startanyshell#1]
In order to add a shell configuration for Cmder, I had to use `%CD%` to start the shell in the current project's directory:

```
"startanyshell.shells": [
  {
    "description": "Cmder",
    "command": "start \"%description%\" cmder.exe /START %CD%"
  }
]
```

Maybe this example could be useful to others.

(Awesome extension by the way!)

**Comment by remcoros** [comment]
I had this in my own config, Added it to the default list as of 0.2.3

```
    {
        "description": "Cmder",
        "command": "cmder.exe /start \"%path%\""
    }
```
