### ISSUE TITLE
Error due to ATOM_SHELL_INTERNAL_RUN_AS_NODE=1

### ISSUE THREAD

**Issue by unional** [remcoros/vscode-startanyshell#2]
I tried to run `browserify test.js | tape-run` on a shell (cmder) started from vscode (in Windows)
It fails with:

``` sh
module.js:340
    throw err;
    ^

Error: Cannot find module 'electron'
```

After some digging, it turns out to be `ATOM_SHELL_INTERNAL_RUN_AS_NODE=1` causes the issue.

Once I remove that env variable, it started working again.

Is there a reason to have that env variable set? Is there a way to disable it?

**Comment by remcoros** [comment]
I don't see this environment variable here, using default launch options of vscode-startanyshell and default cmder settings (latest 1.3). 

It's not something this plugin does, it just executes any of the default or configured commands using 'child_process.exec'.

**Comment by unional** [comment]
It seems to be from electron.

**Comment by remcoros** [comment]
@unional so vscode has come a long way. Is this still an issue ?

**Comment by unional** [comment]
Seems like they have it fixed. 🌷
