### ISSUE TITLE
Cannot work in new version of VSCode 1.5.1

### ISSUE THREAD

**Issue by jamesfancy** [remcoros/vscode-startanyshell#3]
VSCode upgrade automatically today, then "Start any sheel" cannot work. Following picture shows the error.

![image](https://cloud.githubusercontent.com/assets/3953094/18385773/27c84a6a-76c5-11e6-8796-a6fa06e80477.png)

**Comment by remcoros** [comment]
Yeah, got this too today. I'll push an update soon.

**Comment by remcoros** [comment]
I think it's fixed in 1.3.1, can you verify this?

**Comment by jamesfancy** [comment]
> I think it's fixed in 1.3.1, can you verify this?

@remcoros Great, it's fixed exactly.
